### ISSUE TITLE
스트리머가 퇴장 시 뷰어의 퇴장 순서가 보장되지 않는다.

### ISSUE THREAD

**Issue by sukjuhong** [sukjuhong/kwitch#8]
현재 스트리머가 퇴장하면 방이 없어지기 전에 유저의 퇴장 로직이 먼저 실행되야 하는데, 이 순서가 보장되지 않고 유저가 채널을 나가다 방이 없어서 오류가 발생합니다.
순서를 보장 할 필요가 있겠습니다.

뷰어 화면:
![image](https://github.com/user-attachments/assets/21d1c010-2c1b-4848-a409-41967ab538ee)

서버 로그:
```
Streaming ended: be58e9ec-654a-4b08-833f-cba37abf32e2/테스트 방송입니다.
Failed to leave streaming Error: Streaming is not found.
    at m (file:///app/apps/api/dist/index.js:1:7850)
    at T (file:///app/apps/api/dist/index.js:1:7772)
    at Socket.<anonymous> (file:///app/apps/api/dist/index.js:1:9916)
    at Socket.emit (node:events:519:28)
    at Socket.emitUntyped (/app/node_modules/.pnpm/socket.io@4.8.0_bufferutil@4.0.8_utf-8-validate@6.0.4/node_modules/socket.io/dist/typed-events.js:69:22)
    at /app/node_modules/.pnpm/socket.io@4.8.0_bufferutil@4.0.8_utf-8-validate@6.0.4/node_modules/socket.io/dist/socket.js:697:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by sukjuhong** [comment]
추가적으로 toast의 에러 메세지도 잘못 나오고 있습니다.
